import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import StateContextProvider from './items/itemspage-context';

// components
import Navbar from '@/components/navbar/Navbar';

// styling
import "./globals.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: "Remote Configuration Console",
    description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body>
            <main>

                <StateContextProvider>
                    <Navbar/>
                    {children}
                </StateContextProvider>
                
            </main>
        </body>
    </html>
  )
}